version: "3.8"

services:
  kotahi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://kotahi-server:8080
    depends_on:
      - kotahi-server
    restart: unless-stopped
    networks:
      - kotahi-network

  kotahi-server:
    image: kotahi-server:latest # Replace with your actual server image
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/kotahi
      - JWT_SECRET=your-jwt-secret-here
      - PORT=8080
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - kotahi-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=kotahi
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - kotahi-network

networks:
  kotahi-network:
    driver: bridge

volumes:
  mongodb_data:
